version: 0.2

phases:
  pre_build:
    commands:
      - echo "🔐 Logging into Amazon ECR..."
      - aws --version
      - docker --version
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)
      - echo "$IMAGE_TAG" > image_tag.txt
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 160596073886.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo "🔧 Build started on $(date)"
      - IMAGE_TAG=$(cat image_tag.txt)
      - docker build -t 160596073886.dkr.ecr.us-east-1.amazonaws.com/flaskapp-ecs-demo:$IMAGE_TAG .

  post_build:
    commands:
      - IMAGE_TAG=$(cat image_tag.txt)
      - docker push 160596073886.dkr.ecr.us-east-1.amazonaws.com/flaskapp-ecs-demo:$IMAGE_TAG
      - echo "[{\"name\":\"flaskapp-ecs-demo-cluster\",\"imageUri\":\"160596073886.dkr.ecr.us-east-1.amazonaws.com/flaskapp-ecs-demo:$IMAGE_TAG\"}]" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
