version: 0.2

phases:
  pre_build:
    commands:
      - echo "ðŸš€ Starting pre-build phase..."
      - aws sts get-caller-identity
      - aws --version
      - docker --version
      - echo "ðŸ” Logging into Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 160596073886.dkr.ecr.us-east-1.amazonaws.com
      - echo "âœ… Docker login successful"

  build:
    commands:
      - echo "ðŸ”§ Build phase started on `date`"
      - echo "ðŸ›  Building the Docker image..."
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-8)
      - echo "ðŸ–¼ Using image tag: $IMAGE_TAG"
      - docker build -t 160596073886.dkr.ecr.us-east-1.amazonaws.com/flaskapp-ecs-demo:$IMAGE_TAG .

  post_build:
    commands:
      - echo "ðŸ“¤ Pushing the Docker image to ECR..."
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-8)
      - docker push 160596073886.dkr.ecr.us-east-1.amazonaws.com/flaskapp-ecs-demo:$IMAGE_TAG
      - echo "ðŸ“ Creating imagedefinitions.json..."
      - echo "[{\"name\":\"flaskapp-ecs-demo-cluster\",\"imageUri\":\"160596073886.dkr.ecr.us-east-1.amazonaws.com/flaskapp-ecs-demo:$IMAGE_TAG\"}]" > imagedefinitions.json
      - echo "âœ… imagedefinitions.json created."

artifacts:
  files:
    - imagedefinitions.json
