version: 0.2

phases:
  pre_build:
    commands:
      - echo "🚀 Starting pre-build phase..."
      - echo "🔍 Identity:"
      - aws sts get-caller-identity
      - echo "🔍 AWS CLI version:"
      - aws --version
      - echo "🔍 Docker version:"
      - docker --version 
      - echo "🔐 Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 160596073886.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=160596073886.dkr.ecr.us-east-1.amazonaws.com/flaskapp-ecs-demo
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - echo "✅ Logged in and tag will be: $IMAGE_TAG"

  build:
    commands:
      - echo "🔧 Build phase started on `date`"
      - echo "🛠 Building the Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo "✅ Image built: $REPOSITORY_URI:$IMAGE_TAG"

  post_build:
    commands:
      - echo "📦 Post-build phase started on `date`"
      - echo "📤 Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "✅ Image pushed to: $REPOSITORY_URI:$IMAGE_TAG"
      - echo "📝 Creating imagedefinitions.json..."
      - printf '[{"name":"flaskapp-ecs-demo","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "✅ imagedefinitions.json created."

artifacts:
  files:
    - imagedefinitions.json
