version: 0.2

phases:
  pre_build:
    commands:
      - echo "🚀 Starting pre-build phase..."
      - aws sts get-caller-identity
      - aws --version
      - docker --version
      - echo "🔐 Logging into Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 160596073886.dkr.ecr.us-east-1.amazonaws.com
      - echo "✅ Docker login successful"

  build:
    commands:
      - echo "🔧 Build phase started on `date`"
      - echo "🛠 Creating image tag using head..."
      - echo IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8) > image_tag.txt
      - source image_tag.txt
      - echo "🛠 Building Docker image..."
      - docker build -t 160596073886.dkr.ecr.us-east-1.amazonaws.com/flaskapp-ecs-demo:$IMAGE_TAG .

  post_build:
    commands:
      - echo "📤 Pushing Docker image to ECR..."
      - source image_tag.txt
      - docker push 160596073886.dkr.ecr.us-east-1.amazonaws.com/flaskapp-ecs-demo:$IMAGE_TAG
      - echo "📝 Writing imagedefinitions.json..."
      - echo "[{\"name\":\"flaskapp-ecs-demo-cluster\",\"imageUri\":\"160596073886.dkr.ecr.us-east-1.amazonaws.com/flaskapp-ecs-demo:$IMAGE_TAG\"}]" > imagedefinitions.json
      - echo "✅ imagedefinitions.json created."
      - rm image_tag.txt

artifacts:
  files:
    - imagedefinitions.json
