version: 0.2

phases:
  pre_build:
    commands:
      - echo "🔐 Logging in to Amazon ECR..."
      - aws --version
      - docker --version
      - export AWS_ACCOUNT_ID=160596073886
      - export AWS_REGION=us-east-1
      - export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/flaskapp-ecs-demo
      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)
      - echo "🧾 Image tag will be: $IMAGE_TAG"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "🔧 Build started on $(date)"
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "📤 Pushing image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "📝 Writing imagedefinitions.json for ECS..."
      - printf '[{"name":"flaskapp-ecs-demo-cluster","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
