version: 0.2

phases:
  pre_build:
    commands:
      - echo "ðŸš€ Starting pre-build phase..."
      - aws sts get-caller-identity
      - aws --version
      - docker --version
      - echo "ðŸ” Logging into Amazon ECR..."
      - >
        aws ecr get-login-password --region us-east-1 |
        docker login --username AWS --password-stdin 160596073886.dkr.ecr.us-east-1.amazonaws.com
      - echo "âœ… Docker login successful"

  build:
    commands:
      - echo "ðŸ”§ Build phase started on `date`"
      - echo "ðŸ›  Building the Docker image..."
      - >
        docker build -t 160596073886.dkr.ecr.us-east-1.amazonaws.com/flaskapp-ecs-demo:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8) .

  post_build:
    commands:
      - echo "ðŸ“¤ Pushing the Docker image to ECR..."
      - >
        docker push 160596073886.dkr.ecr.us-east-1.amazonaws.com/flaskapp-ecs-demo:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)
      - echo "ðŸ“ Creating imagedefinitions.json..."
      - >
        printf '[{"name":"flaskapp-ecs-demo-cluster","imageUri":"160596073886.dkr.ecr.us-east-1.amazonaws.com/flaskapp-ecs-demo:%s"}]' $(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8) > imagedefinitions.json
      - echo "âœ… imagedefinitions.json created."

artifacts:
  files:
    - imagedefinitions.json
