version: 0.2

phases:
  pre_build:
    commands:
      - echo "🚀 Starting pre-build phase..."
      - aws sts get-caller-identity
      - aws --version
      - docker --version
      - echo "🔐 Logging into Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 160596073886.dkr.ecr.us-east-1.amazonaws.com
      - echo "✅ Docker login successful"
      - REPOSITORY_URI=160596073886.dkr.ecr.us-east-1.amazonaws.com/flaskapp-ecs-demo
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)
      - echo "📛 Image tag: $IMAGE_TAG"

  build:
    commands:
      - echo "🔧 Build phase started on `date`"
      - echo "🛠 Building the Docker image..."
      - docker build -t 160596073886.dkr.ecr.us-east-1.amazonaws.com/flaskapp-ecs-demo:$IMAGE_TAG .
      
  post_build:
    commands:
      - echo "📤 Pushing the Docker image to ECR..."
      - docker push 160596073886.dkr.ecr.us-east-1.amazonaws.com/flaskapp-ecs-demo:$IMAGE_TAG
      - echo "📝 Creating imagedefinitions.json..."
      - printf '[{"name":"flaskapp-ecs-demo-cluster","imageUri":"160596073886.dkr.ecr.us-east-1.amazonaws.com/flaskapp-ecs-demo:%s"}]' $IMAGE_TAG > imagedefinitions.json
      - echo "✅ Image pushed and definition file written"

artifacts:
  files:
    - imagedefinitions.json
